server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
            predicates:
              - Path=/user/**
        - id: car-service
          uri: lb://car-service
            predicates:
              - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
            predicates:
              - Path=/bike/**
